# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 745529edf4d30d5d87735c25414687c1a523f8114520145701c4c2ffb4795982f39613be069d2f01cddfa060342b07c314d07472928f9e5fe01e09779ccee1ad

test:
  secret_key_base: 547cb28daf6f4813657959d89c8064e1908d24a666b02fe6d9b9941e6ce2a05a53c2708e91e4d923e84b8e35ca6adcf1a3f486ade47e8b07405978412a4c9606

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
